import { useRepo } from "../../context/repository/repo-context"

export function useRepoStatus() {
  const repo = useRepo()
  return {
    repo: repo.repo,
    repoName: repo.repoName,
    status: repo.status,
    branches: repo.branches,
    localBranches: repo.localBranches,
    tags: repo.tags,
    remotes: repo.remotes,
    log: repo.log,
    graph: repo.graph,
    busy: repo.busy,
    opening: repo.opening,
    msg: repo.msg,
    setMsg: repo.setMsg,
    gitVersion: repo.gitVersion,
    remoteUrl: repo.remoteUrl,
    gpg: repo.gpg,
    unmergedCount: repo.unmergedCount,
    refresh: repo.refresh,
    lastError: repo.lastError,
    clearError: repo.clearError,
    handleOpen: repo.handleOpen,
    handleBrowse: repo.handleBrowse,
    pickDir: repo.pickDir,
    cloneRepo: repo.cloneRepo,
    checkoutBranch: repo.checkoutBranch,
    deleteBranch: repo.deleteBranch,
    renameBranch: repo.renameBranch,
    fetchPrune: repo.fetchPrune,
    createTag: repo.createTag,
    deleteTag: repo.deleteTag,
    addRemote: repo.addRemote,
    removeRemote: repo.removeRemote,
    pullIt: repo.pullIt,
    pushIt: repo.pushIt,
    amendCommit: repo.amendCommit,
    loadMoreLog: repo.loadMoreLog,
    loadMoreGraph: repo.loadMoreGraph,
    logLoading: repo.logLoading,
    graphLoading: repo.graphLoading,
    logHasMore: repo.logHasMore,
    graphHasMore: repo.graphHasMore,
    openTerminalHint: repo.openTerminalHint,
    pendingConfirm: repo.pendingConfirm,
    requestConfirm: repo.requestConfirm,
    recents: repo.recents,
    openRecent: repo.openRecent,
    clearRecents: repo.clearRecents,
    removeRecent: repo.removeRecent,
  }
}

export type RepoStatusApi = ReturnType<typeof useRepoStatus>
