import { useMemo } from "react"
import { mergeStats } from "../../../main/adapters"
import type { Lang } from "../../../types"
import { useMerge } from "../merge/useMerge"
import { useRepoCore } from "./useRepoCore"
import { useStaging } from "./useStaging"

export type { View } from "./useRepoCore"

export function useRepository(lang: Lang) {
  const core = useRepoCore(lang)
  const staging = useStaging({
    lang,
    repo: core.repo,
    runAction: core.runAction,
    requestConfirm: core.requestConfirm,
    setMsg: core.setMsg,
  })
  const merge = useMerge({
    lang,
    repo: core.repo,
    status: core.status,
    conflicts: core.conflicts,
    setConflicts: core.setConflicts,
    refresh: core.refresh,
    runAction: core.runAction,
    setBusy: core.setBusy,
    setMsg: core.setMsg,
    readCommitMessage: () => staging.commitMsg,
    clearCommitMessage: () => staging.setCommitMsg(""),
  })

  const stats = useMemo(() => mergeStats(core.conflicts, merge.resolvedMap), [core.conflicts, merge.resolvedMap])
  const unmergedCount = useMemo(
    () => core.status?.files.filter((f) => f.unmerged).length ?? core.conflicts.length,
    [core.status, core.conflicts.length],
  )

  return {
    repoInput: core.repoInput,
    setRepoInput: core.setRepoInput,
    repo: core.repo,
    recents: core.recents,
    openRecent: core.openRecent,
    clearRecents: core.clearRecents,
    removeRecent: core.removeRecent,
    status: core.status,
    branches: core.branches,
    localBranches: core.localBranches,
    tags: core.tags,
    remotes: core.remotes,
    log: core.log,
    graph: core.graph,
    totalCommits: core.totalCommits,
    conflicts: core.conflicts,
    activeConflict: merge.activeConflict,
    editorContent: merge.editorContent,
    setEditorContent: merge.setEditorContent,
    selectedFile: staging.selectedFile,
    diff: staging.diff,
    diffStaged: staging.diffStaged,
    diffLoaded: staging.diffLoaded,
    diffLoading: staging.diffLoading,
    diffError: staging.diffError,
    blameFile: staging.blameFile,
    blameLines: staging.blameLines,
    trackedFiles: staging.trackedFiles,
    loadBlame: staging.loadBlame,
    loadTracked: staging.loadTracked,
    commitMsg: staging.commitMsg,
    setCommitMsg: staging.setCommitMsg,
    busy: core.busy,
    opening: core.opening,
    msg: core.msg,
    setMsg: core.setMsg,
    lastError: core.lastError,
    clearError: core.clearError,
    mergeBranch: merge.mergeBranch,
    setMergeBranch: merge.setMergeBranch,
    mergeSquash: merge.mergeSquash,
    setMergeSquash: merge.setMergeSquash,
    mergeNoFF: merge.mergeNoFF,
    setMergeNoFF: merge.setMergeNoFF,
    newBranch: staging.newBranch,
    setNewBranch: staging.setNewBranch,
    stashMsg: staging.stashMsg,
    setStashMsg: staging.setStashMsg,
    gitVersion: core.gitVersion,
    remoteUrl: core.remoteUrl,
    gpg: core.gpg,
    resolvedMap: merge.resolvedMap,
    stats,
    repoName: core.repoName,
    unmergedCount,
    refresh: core.refresh,
    handleOpen: core.handleOpen,
    handleBrowse: core.handleBrowse,
    pickDir: core.pickDir,
    cloneRepo: core.cloneRepo,
    loadDiff: staging.loadDiff,
    selectDiff: staging.selectDiff,
    runAction: core.runAction,
    doCommit: staging.doCommit,
    saveConflictFile: merge.saveConflictFile,
    resolveConflictFile: merge.resolveConflictFile,
    continueMerge: merge.continueMerge,
    startMerge: merge.startMerge,
    selectConflictFile: merge.selectConflictFile,
    checkoutBranch: core.checkoutBranch,
    deleteBranch: core.deleteBranch,
    renameBranch: core.renameBranch,
    fetchPrune: core.fetchPrune,
    createTag: core.createTag,
    deleteTag: core.deleteTag,
    addRemote: core.addRemote,
    removeRemote: core.removeRemote,
    createBranch: staging.createBranch,
    stashPush: staging.stashPush,
    stashPopIt: staging.stashPopIt,
    stageFile: staging.stageFile,
    unstageFile: staging.unstageFile,
    discardFile: staging.discardFile,
    stageHunk: staging.stageHunk,
    unstageHunk: staging.unstageHunk,
    discardHunk: staging.discardHunk,
    stageSelected: staging.stageSelected,
    unstageSelected: staging.unstageSelected,
    stageAll: staging.stageAll,
    editingFile: staging.editingFile,
    editContent: staging.editContent,
    editDraft: staging.editDraft,
    setEditDraft: staging.setEditDraft,
    editLoading: staging.editLoading,
    openEditor: staging.openEditor,
    closeEditor: staging.closeEditor,
    saveEditor: staging.saveEditor,
    pullIt: core.pullIt,
    pushIt: core.pushIt,
    amendCommit: core.amendCommit,
    loadMoreLog: core.loadMoreLog,
    loadMoreGraph: core.loadMoreGraph,
    logLoading: core.logLoading,
    graphLoading: core.graphLoading,
    logHasMore: core.logHasMore,
    graphHasMore: core.graphHasMore,
    abortMerge: merge.abortMerge,
    openTerminalHint: core.openTerminalHint,
    pendingConfirm: core.pendingConfirm,
    requestConfirm: core.requestConfirm,
    reflog: core.reflog,
    reflogLoading: core.reflogLoading,
    reflogLoaded: core.reflogLoaded,
    loadReflog: core.loadReflog,
    cherryPick: core.cherryPick,
    cherryPickContinue: core.cherryPickContinue,
    cherryPickAbort: core.cherryPickAbort,
    revert: core.revert,
    revertContinue: core.revertContinue,
    revertAbort: core.revertAbort,
    resetBranch: core.resetBranch,
    loadCommitFiles: core.loadCommitFiles,
    loadCommitDiff: core.loadCommitDiff,
    stashes: staging.stashes,
    loadStashes: staging.loadStashes,
    stashApply: staging.stashApply,
    stashDrop: staging.stashDrop,
    stashShow: staging.stashShow,
    submodules: staging.submodules,
    loadSubmodules: staging.loadSubmodules,
    submoduleUpdate: staging.submoduleUpdate,
  }
}

export type Repository = ReturnType<typeof useRepository>
