import type { BlockCategoryId, BlockTemplate, ConditionKind } from "../../domain/entities/automations/automations"

export const MONITOR_BLOCK_TEMPLATES: readonly BlockTemplate[] = [
  {
    id: "git-pull",
    label: "Git Pull",
    icon: "ArrowDown",
    color: "#10b981",
    category: "git",
    defaultCommands: ["git pull"],
  },
  {
    id: "git-push",
    label: "Git Push",
    icon: "ArrowUp",
    color: "#3b82f6",
    category: "git",
    defaultCommands: ["git push"],
  },
  {
    id: "git-fetch",
    label: "Git Fetch",
    icon: "Download",
    color: "#8b5cf6",
    category: "git",
    defaultCommands: ["git fetch --all --prune"],
  },
  {
    id: "git-status",
    label: "Git Status",
    icon: "FileText",
    color: "#f59e0b",
    category: "git",
    defaultCommands: ["git status --short"],
  },
  {
    id: "git-fetch-all",
    label: "Git Fetch All",
    icon: "Download",
    color: "#3b82f6",
    category: "git",
    defaultCommands: ["git fetch --all --prune"],
  },
  {
    id: "git-pull-rebase",
    label: "Git Pull Rebase",
    icon: "ArrowUp",
    color: "#8b5cf6",
    category: "git",
    defaultCommands: ["git pull --rebase"],
  },
  {
    id: "git-submodule-update",
    label: "Submodule Update",
    icon: "Package",
    color: "#ec4899",
    category: "submodule",
    defaultCommands: ["git submodule update --init --recursive"],
  },
  {
    id: "git-submodule-foreach-pull",
    label: "Submodule Foreach Pull",
    icon: "GitBranch",
    color: "#ec4899",
    category: "submodule",
    defaultCommands: ["git submodule foreach 'git pull origin master'"],
  },
  {
    id: "npm-install",
    label: "NPM Install",
    icon: "Package",
    color: "#cb3837",
    category: "node",
    defaultCommands: ["npm install"],
  },
  {
    id: "npm-build",
    label: "NPM Build",
    icon: "Zap",
    color: "#f59e0b",
    category: "node",
    defaultCommands: ["npm run build"],
  },
  {
    id: "npm-test",
    label: "NPM Test",
    icon: "Check",
    color: "#10b981",
    category: "node",
    defaultCommands: ["npm test"],
  },
  {
    id: "npm-run-dev",
    label: "NPM Run Dev",
    icon: "Play",
    color: "#f59e0b",
    category: "node",
    defaultCommands: ["npm run dev"],
  },
  {
    id: "docker-compose-up",
    label: "Docker Compose Up",
    icon: "Database",
    color: "#0ea5e9",
    category: "docker",
    defaultCommands: ["docker compose up -d"],
  },
  {
    id: "docker-compose-down",
    label: "Docker Compose Down",
    icon: "Download",
    color: "#ef4444",
    category: "docker",
    defaultCommands: ["docker compose down"],
  },
  {
    id: "custom",
    label: "Custom Command",
    icon: "Terminal",
    color: "#64748b",
    category: "custom",
    defaultCommands: [""],
  },
]

export const BLOCK_CATEGORIES: readonly {
  id: BlockCategoryId
  label: string
  icon: string
}[] = [
  { id: "git", label: "Git", icon: "GitBranch" },
  { id: "submodule", label: "Submodules", icon: "GitBranch" },
  { id: "node", label: "Node.js", icon: "Package" },
  { id: "docker", label: "Docker", icon: "Database" },
  { id: "custom", label: "Custom", icon: "Terminal" },
]

export const CONDITION_KINDS: readonly ConditionKind[] = [
  "branch-exists",
  "tag-exists",
  "clean",
  "submodule-ready",
  "command-ok",
]

export const KNOWN_GIT_VERBS = new Set([
  "pull",
  "push",
  "fetch",
  "status",
  "add",
  "commit",
  "merge",
  "rebase",
  "checkout",
  "switch",
  "branch",
  "tag",
  "log",
  "diff",
  "stash",
  "submodule",
  "remote",
  "config",
  "reset",
  "clean",
  "ls-files",
  "show",
  "blame",
  "bisect",
  "cherry-pick",
  "apply",
  "am",
  "format-patch",
  "send-email",
  "archive",
  "bundle",
  "verify-commit",
  "verify-tag",
  "worktree",
  "sparse-checkout",
  "maintenance",
  "grep",
  "shortlog",
  "describe",
  "name-rev",
  "notes",
  "replace",
  "update-ref",
  "symbolic-ref",
  "for-each-ref",
  "count-objects",
  "prune",
  "reflog",
  "fsck",
  "gc",
  "pack-objects",
  "unpack-objects",
  "index-pack",
  "write-tree",
  "read-tree",
  "commit-tree",
  "mktree",
  "cat-file",
  "hash-object",
  "ls-tree",
  "rev-parse",
  "rev-list",
  "merge-base",
  "show-ref",
  "check-ref-format",
  "init",
  "clone",
  "daemon",
  "receive-pack",
  "upload-pack",
  "upload-archive",
  "shell",
])
